### ISSUE TITLE
[suggestion] More docs on robot connection and ros setup without docker.

### ISSUE THREAD

**Issue by xarthurx** [gramaziokohler/compas_fab#38]
Summary.

Currently, all setup on the ros side is provided by the dockers built by the group.
However, this is very limited to the tasks one need.

Would it be possible to add more documentation on this? 

Issues like:
https://github.com/gramaziokohler/compas_fab/issues/5
https://github.com/gramaziokohler/compas_fab/issues/6

seems to be lost of track?

**Comment by gonzalocasas** [comment]
Added docs on [ROS setup](https://gramaziokohler.github.io/compas_fab/latest/backends/ros.html] including Linux, WSL and Docker setup options. Eventually, a documented Raspberry Pi setup would be great.
