### ISSUE TITLE
Robot control via ROS: UR

### ISSUE THREAD

**Issue by gonzalocasas** [gramaziokohler/compas_fab#5]
- [ ] Generic control API
- [ ] Pack UR drivers and ROS setup
- [ ] UR control implementation

**Comment by xarthurx** [comment]
has this been implemented or not? 
1.5 years from now.

**Comment by gonzalocasas** [comment]
yep, we need to clean up old issues. This is done based on the ROS UR drivers (so there's no explicit implementation on `compas_fab`) but it would make sense to add more examples on how to actually setup this. @romanarust is working on a pull request that will add a few more details to the documentation in this front, but we might still need to extend it in the future.
